name: Release
on:
  push:
    tags: ["v*"]
permissions:
  actions: read
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    uses: EsionHsrahLatigid/yup-actions/.github/workflows/plugin-release.yml@d06448066a4d9fa7202851d7764fa92ea48d4ce4
    with:
      product_name: ZeroJet
